---

- hosts: all
  become: yes

  tasks:

# https://docs.debops.org/en/stable-2.3/ansible/roles/python/defaults/main.html

  - name: install python3 packages
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
        - 'python3'
        - 'python3-apt'
        - 'python3-httplib2'
        - 'python3-pip'
        - 'python3-setuptools'
        - 'python3-pycurl'
        - 'python3-future'
        - 'python3-virtualenv'
        - 'python3-wheel'
        - 'virtualenv'
